server:
  port: 8003

spring:
  application:
    name: translate-service

# DeepSeek API配置
deepseek:
  api:
    url: ${DEEPSEEK_API_URL:https://api.deepseek.com}
    key: ${DEEPSEEK_API_KEY:}
    timeout:
      seconds: ${DEEPSEEK_TIMEOUT:30}
  model: ${DEEPSEEK_MODEL:deepseek-chat}

# 翻译服务配置
translation:
  # 缓存配置
  cache:
    enabled: true
    ttl-seconds: 3600  # 缓存1小时
    max-size: 10000
  
  # 线程池配置
  thread:
    pool:
      size: ${TRANSLATION_THREAD_POOL_SIZE:10}
      max-size: 20
      queue-capacity: 100
  
  # 质量控制
  quality:
    enable-assessment: true
    min-confidence: 0.7
    enable-validation: true
  
  # 批量处理限制
  batch:
    max-texts: 100
    max-text-length: 5000
    parallel-processing: true
  
  # 重试配置
  retry:
    max-attempts: 3
    delay-ms: 1000
    backoff-multiplier: 2.0

# 文本校验配置
validation:
  # 相似度计算配置
  similarity:
    algorithm:
      levenshtein:
        weight: 0.4
      jaccard:
        weight: 0.3
      cosine:
        weight: 0.3
    
    # 默认阈值
    default-threshold: 0.8
    
    # 模式阈值
    thresholds:
      strict: 0.9
      normal: 0.8
      lenient: 0.6
  
  # 语言检测配置
  language-detection:
    confidence-threshold: 0.7
    min-text-length: 10
  
  # 关键词验证配置
  keyword:
    enable-validation: true
    case-sensitive: false
    partial-match: true

# 支持的语言配置
languages:
  primary:
    - code: zh-CN
      name: 简体中文
      iso639: zh
    - code: zh-TW
      name: 繁体中文
      iso639: zh-tw
    - code: en
      name: English
      iso639: en
    - code: ja
      name: 日本語
      iso639: ja

# HTTP客户端配置
http:
  client:
    connect-timeout: 30000
    read-timeout: 30000
    max-connections: 100
    max-connections-per-route: 20

# 消息队列配置
message:
  queue:
    broker-url: vm://localhost
    user: admin
    password: admin

# 日志配置
logging:
  level:
    com.translation.translate: DEBUG
    com.translation.translate.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{50}] - %msg%n"

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true

# 性能监控
metrics:
  translation:
    enable-timing: true
    enable-counting: true
    histogram-buckets: 0.1,0.5,1.0,2.0,5.0,10.0
